# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-07 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CameraLocaiton',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('camera_id', models.IntegerField()),
                ('address', models.CharField(max_length=256)),
                ('longitude', models.CharField(max_length=32)),
                ('latitude', models.CharField(max_length=32)),
            ],
            options={
                'ordering': ['-camera_id'],
                'db_table': 'camera_location',
                'managed': False,
            },
        ),
    ]
